[WIP] Create backend contrib packages
maykinmedia/open-personen pull request #113
Opened 2020-10-06 13:34 UTC by shea-maykinmedia

Fixes #82 
Fixes #83

2020-10-08 11:58 UTC, joeribekker requested changes

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/conf/base.py
>              os.path.join(DJANGO_PROJECT_DIR, "api/tests/response_templates"),
Hmm, let's enable APP_DIRS so all these are not needed. Custom loaders are not needed in this project.

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/conf/base.py
>  OPENPERSONEN_DAY_END = 8
Can you add a comment here what this means? I already forgot.

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/api/data_classes/persoon.py
> +        function = getattr(backend, cls.backend_function_name)
rename to `func` to prevent conflicts.

```suggestion
        func = getattr(backend, cls.backend_function_name)
```

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/api/data_classes/partner_historie.py
> +from openpersonen.contrib.stufbg.models import StufBGClient
I see this class wasn't refactored yet?

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/api/data_classes/verblijf_plaats_historie.py
> +from openpersonen.contrib.stufbg.models import StufBGClient
This class also needs refactoring

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/api/data_classes/verblijfs_titel_historie.py
> +from openpersonen.contrib.stufbg.models import StufBGClient
This class also needs refactoring

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/api/tests/views/test_ingeschrevenpersoon.py
> +    @patch(
You can patch on class level.

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/api/tests/views/test_kind.py
> +    @patch(
also here, you can patch on class level.

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/api/tests/views/test_kind.py
> +        self.assertEqual(response.status_code, 404)
Out of interest: Why did this succeed before?

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/api/tests/views/test_permissions.py
>  class TestPermissions(APITestCase):
Few obsolete override settings here.

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/conf/base.py
>      OPENPERSONEN_USE_AUTHENTICATION = (
Let's replace this with:

```
    OPENPERSONEN_USE_AUTHENTICATION = config(
        "OPENPERSONEN_USE_AUTHENTICATION", True)
```

See here for the `config` function: https://github.com/open-zaak/open-zaak/blob/master/src/openzaak/conf/includes/environ.py

Also, I replaced the default now with `True`. I think the default false via Docker-compose is more safe.

Which reminds me, OPENPERSONEN_BACKEND should be in Docker-compose :)

2020-10-08 11:58 UTC, joeribekker commented on src/openpersonen/contrib/demo/__init__.py
> +from .backend import BackEnd
I don't recommend this in the `__init__` since those are autoloaded and we only need to load it when its configured in the settings. It can be as last line in the backend.py file and can name the variable `default`. This way your settings would become

`OPENPERSONEN_BACKEND="openpersonen.contrib.demo.backend.default"`

and the class is not needlessly autoloaded.

2020-10-08 12:21 UTC, shea-maykinmedia commented on src/openpersonen/api/tests/views/test_kind.py
> +        self.assertEqual(response.status_code, 404)
It would succeed because it would return an empty response but I think a 404 is what actually should be returned.

2020-10-09 08:45 UTC, shea-maykinmedia commented on src/openpersonen/conf/base.py
>              os.path.join(DJANGO_PROJECT_DIR, "api/tests/response_templates"),
I think I did what you requested but I'm not sure.  I removed the 'loaders' key in the 'OPTIONS' field and removed the custom loaders but I've kept the three paths in the 'DIRS' field.  Can you let me know if this is correct or if you meant something else.

2020-10-11 08:59 UTC, joeribekker commented on src/openpersonen/conf/base.py
>              os.path.join(DJANGO_PROJECT_DIR, "api/tests/response_templates"),
I don't think the app paths are needed (except the general templates one). These are auto added by APP_DIRS=True.

So these can be out:
```
            os.path.join(DJANGO_PROJECT_DIR, "contrib/stufbg/request_templates"),
            os.path.join(DJANGO_PROJECT_DIR, "api/tests/response_templates"),
```

2020-10-12 09:48 UTC, shea-maykinmedia commented
@joeribekker I believe I addressed all your feedback.  Can you take another look when you have the chance.

2020-10-17 12:11 UTC, joeribekker approved these changes

2020-10-19 07:01 UTC, merged