[WIP] Add expand property
maykinmedia/open-personen pull request #131
Opened 2020-10-19 13:38 UTC by shea-maykinmedia

2020-10-22 08:02 UTC, shea-maykinmedia commented
I'm temporarily converting this to a draft since a small change needs to be made.  The code won't change much but I think it's worth making that change before anyone reviews it.

2020-10-23 09:59 UTC, shea-maykinmedia commented
@stevenbal The pull request is ready to review whenever you have time :)

2020-10-23 12:27 UTC, stevenbal requested changes

2020-10-23 12:27 UTC, stevenbal commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +        for partner in instance.partners:
I think you could combine these three loops like this:

```python
for field in self.expand_fields:
    representation[f"{field}_links"] = []
    for obj in getattr(instance, field):
        representation[f"{field}_links"].append(
            {
                 "url": self.context["request"]
                 .build_absolute_uri(self.context["request"].path)
                 .replace(
                     f"/{instance.burgerservicenummer}", 
                     f"/{instance.burgerservicenummer}/{field}/{obj['burgerservicenummer']}"
                 )
            }
        )
```

2020-10-23 12:27 UTC, stevenbal commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +        for index, field_key in enumerate(split_params[:-1]):
Just to check: can the dotted path have more than one attribute, like: `resource.attribute1.nested_attribute`? In the [feature description](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/expand.feature) I only saw examples with one attribute, so I'm not sure if we only need to support that? (Would simplify the code a bit if that is the case)

2020-10-23 13:40 UTC, shea-maykinmedia commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +        for index, field_key in enumerate(split_params[:-1]):
Yes, this scenario https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/expand.feature#L129 gives kinderen.naam.voornamen and kinderen.naam.geslachtsnaam as example cases that need to be handled. 

I do agree the code would be simplier if we didn't need to support this though ;P

2020-10-23 14:13 UTC, stevenbal commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +                               + f"/{instance.burgerservicenummer}/{field}/{obj['burgerservicenummer']}"
Can't you replace it with the correct path directly, instead of replacing it with an empty string and then appending? Or just skip the replace and append `f"/{instance.burgerservicenummer}/{field}/{obj['burgerservicenummer']}"`?
```suggestion
"url": self.context["request"].build_absolute_uri(self.context["request"].path).replace(
                            f'/{instance.burgerservicenummer}', f"/{instance.burgerservicenummer}/{field}/{obj['burgerservicenummer']}")
```

2020-10-23 14:17 UTC, shea-maykinmedia commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +                               + f"/{instance.burgerservicenummer}/{field}/{obj['burgerservicenummer']}"
`self.context["request"].build_absolute_uri(self.context["request"].path)` won't always have the instance's burgerservicenummer.  It depends on whether the url you call is `/api/ingeschrevenpersonen/` which does not have it while `/api/ingeschrevenpersonen/{burgerservicenummer}` does have it.  

For this reason we can't rely on the burgerservicenummer being there which is why I remove it if it is there and then always add it back.

2020-10-23 14:18 UTC, shea-maykinmedia commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +                               + f"/{instance.burgerservicenummer}/{field}/{obj['burgerservicenummer']}"
So ideally what I want is to always return the url `/api/ingeschrevenpersonen/` but I don't know of a way to do this when calling `/api/ingeschrevenpersonen/{burgerservicenummer}` which is why I do the replace with an empty string to remove it.

2020-10-23 14:19 UTC, stevenbal commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +                               + f"/{instance.burgerservicenummer}/{field}/{obj['burgerservicenummer']}"
Ahh I see, then it's good :+1:

2020-10-23 14:19 UTC, stevenbal approved these changes

2020-10-23 14:23 UTC, shea-maykinmedia commented
Travis seems frozen but the jobs all pass locally so I'm going to merge this

2020-10-23 14:23 UTC, merged