[WIP] Add fields property
maykinmedia/open-personen pull request #133
Opened 2020-10-23 10:48 UTC by shea-maykinmedia

Fixes #129 

Relies on `add-expand-property` being merged first so I'll leave this as a Draft until then

2020-10-26 13:37 UTC, stevenbal requested changes
Looks good overall, just some minor comments

2020-10-26 13:37 UTC, stevenbal commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +
From what I understand (from https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/fields.feature#L57), the behavior should be:
* If the `fields` parameter is not supplied, all `_links` should be returned (so for all `self.expand_fields`)
* If the `fields` parameter is supplied, but `_links` is not included in `fields`, only `_links.self` should be returned

I think I would do it like this (although I'm not quite sure if `_links.self` needs to be added to this, or whether that is handled somewhere else):

```python
def add_links(self, instance, representation)
    fields = self.context["request"].GET.get("fields", "").split(",")
        
    for expand_field in self.expand_fields:
        if fields:
            for field in fields:
                # Only add if field is specified in `fields` parameter
                if "_links" in fields and expand_field in field.split(".")[1]:
                    self.add_field_links(instance, representation, expand_field)
        else:
             # No `fields` parameter supplied, simply add all fields
             self.add_field_links(instance, representation, expand_field)
```

2020-10-26 15:10 UTC, shea-maykinmedia commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +            self.fields.pop(field)
I don't think this one will work because you're modifying `self.fields` as you're looping over it so python will throw a `RuntimeError`

2020-10-26 15:12 UTC, shea-maykinmedia commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +                self.fields[field].fields.pop(inner_field)
Similar to the comment above.  This causes a `RuntimeError` because we're modifying `self.fields[field].fields` by calling `pop` as we're looping over it.

2020-10-26 15:34 UTC, shea-maykinmedia commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +
Yes, you are right about the behaviour of `_links` and `fields`

2020-10-26 15:35 UTC, shea-maykinmedia commented on src/openpersonen/api/tests/views/test_ingeschrevenpersoon.py
> +        self.assertEqual(response.json(), get_expand_400_response(url, "bestaatniet"))
Yes, I'll update this.  It's not that generic but is generic enough to use for the fields property so I'll update this name.

2020-10-26 16:23 UTC, stevenbal commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +            self.fields.pop(field)
Ah that's right, I guess to circumvent that you could do this:

```python
from copy import deepcopy

fields = deepcopy(self.fields)

for field in fields:
    if field not in fields_to_keep:
         self.fields.pop(field)
```

2020-10-26 16:24 UTC, stevenbal approved these changes

2020-10-27 08:03 UTC, shea-maykinmedia commented on src/openpersonen/api/serializers/ingeschreven_personen.py
> +            self.fields.pop(field)
Ah ya, that's a good solution.

2020-10-27 13:35 UTC, merged