Implement private media folder
maykinmedia/open-personen pull request #141
Opened 2020-10-29 10:33 UTC by shea-maykinmedia

Solution for last point of https://github.com/maykinmedia/open-personen/issues/140

Uses django-privates to securely store and transfer certificates and certificate keys when making external requests to StUF-BG.

2020-10-29 11:18 UTC, sergei-maertens requested changes

2020-10-29 11:18 UTC, sergei-maertens commented on default.conf
> +    }
Sample nginx config is missing the internal location for the private media root, see https://github.com/open-zaak/ansible-collection/blob/master/roles/open_zaak_k8s/templates/nginx-config.yml.j2#L70 for an example

2020-10-29 11:42 UTC, shea-maykinmedia commented on default.conf
> +    }
I've added this below and I believe it's correct.  When in the web docker container I see

```bash
maykin@4b454aff7ef6:/app$ ls
log  media  private-media  src	static
```

2020-10-29 14:39 UTC, sergei-maertens commented on default.conf
> +    }
yeah, it also depends on the volume shared by web/nginx being mounted in the correct locations!

2020-10-29 14:40 UTC, sergei-maertens requested changes
docker-compose volumes are missing

2020-10-29 16:56 UTC, shea-maykinmedia commented on Dockerfile
> -
I'm not exactly why these lines are in the Dockerfile by default.  

With the private-media these lines caused a 500 because the owner of the private-media directory was `root` and not the `maykin` user.

2020-10-29 16:59 UTC, shea-maykinmedia commented
I _think_ the docker mounts are set up properly now.  I followed https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/blob/master/docker-compose.override.yml and https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/blob/master/docker-compose.yml as an example.

After saving the certificate and certificate key I see in them saved in the web and nginx container

Web
```bash
root@2adc9501c905:/app/private-media/certificate# ls
fake.cert  fake.key
```

Nginx
```bash
root@3fdea2bf7631:/private-media/certificate# ls
fake.cert  fake.key
```

2020-11-02 09:16 UTC, sergei-maertens commented on Dockerfile
> -
we drop privileges so that the container user does not run as root by default. Usually we change the volume permissions using Ansible or ensure that the group is shared. Please restore this line, there is no reason for the container user to be root.

2020-11-02 16:09 UTC, shea-maykinmedia commented
@sergei-maertens Added busybox to modify the permissions of the docker volume.  I tested uploading a fake certificate and key through the admin as well as testing the with the stufbg backend through postman and both worked properly so I believe this means that the certficates and being written and read correctly.

A question for you and @joeribekker, do we want documentation about the docker volume that is now added?

2020-11-02 16:33 UTC, sergei-maertens commented
Thanks, I expect to be able to look into this on Thursday or Friday!

> A question for you and @joeribekker, do we want documentation about the docker volume that is now added?

I think the only relevant documentation should be that `/app/private-media` must be a Docker volume to hold uploaded files. If not, on container restarts the state is wiped. It's up to the person deploying it to figure out what persistent storage they need - on Kubernetes this would be RWX, but on docker swarm this could look differently. There are too many flavours to handle all this.

It's important the the `docker-compose.yml` shows a viable example configuration, DevOops people can figure out the rest from there usually.

2020-11-03 11:47 UTC, sergei-maertens requested changes

2020-11-03 12:17 UTC, shea-maykinmedia commented on docker-compose-quickstart.yml
> +      - web
I'm just curious, what the reason for having them in both places?  

The only reason I can think of is that someone can specify a different override but if that is the case what's the reason for us having our own `docker-compose.override.yml`?

2020-11-03 15:00 UTC, sergei-maertens commented on docker-compose-quickstart.yml
> +      - web
Because that's the file that's mentioned on https://open-personen.readthedocs.io/en/latest/installation/quickstart.html#installation-quickstart

They don't have the override, since they download the compose file, which in the current situation results in a compose file without volumes

2020-11-03 15:08 UTC, shea-maykinmedia commented on docker-compose-quickstart.yml
> +      - web
Ah right, I forgot that's how we specified the quickstart.

Would it make sense then to get rid of the `docker-compose.overrride.yml` since the volumes will be specified in `docker-compose.yml`?

2020-11-03 15:11 UTC, shea-maykinmedia commented on docker-compose-quickstart.yml
> +      - web
Nevermind, I missed that this file is `docker-compose-quickstart.yml` which is why I was confused :p

2020-11-13 11:03 UTC, sergei-maertens approved these changes

2020-11-13 12:27 UTC, merged