Disable logging to prevent sporadic failure
maykinmedia/open-personen pull request #146
Opened 2020-11-03 10:30 UTC by shea-maykinmedia

Fixes #104 

I'm fairly certain that the reason the travis unit test sporadically fails is because the function `generator.get_schema` logs so much text that it blocks the io stream of travis which causes a failure.

The simplest solution seems to be to disable the logging for this function call and return to normally logging afterwards so the logging can continue as normal.

2020-11-13 11:03 UTC, joeribekker requested changes

2020-11-13 11:03 UTC, joeribekker commented on src/openpersonen/api/tests/views/test_schema.py
> +        logging.disable(logging.NOTSET)
This disables logging for all other tests after this test as well. It needs to be enabled again after the test.

2020-11-13 12:49 UTC, shea-maykinmedia commented on src/openpersonen/api/tests/views/test_schema.py
> +        logging.disable(logging.NOTSET)
I was looking at 

https://docs.python.org/3.7/library/logging.html#logging.disable

and specifically this line 

```
If logging.disable(logging.NOTSET) is called, it effectively removes this overriding level, so that logging output again depends on the effective levels of individual loggers.
```

So I though that this will change the logging back to what it was before?

2020-11-16 09:20 UTC, joeribekker commented on src/openpersonen/api/tests/views/test_schema.py
> +        logging.disable(logging.NOTSET)
Oops you're right.

2020-11-16 09:20 UTC, joeribekker approved these changes

2020-11-16 09:26 UTC, merged