Get input from user
maykinmedia/open-personen pull request #152
Opened 2020-11-12 08:41 UTC by shea-maykinmedia

Fixes #147 

Now we ask a user for input if their user already has a token.

Example usage

```bash
# First time generating the token, not asking for feedback
(env) shea@Sheas-MacBook-Pro open-personen % python src/manage.py generate_token user2 
API token: a60fa63477e695e49a1a3d05c6a26571e027b0ec

# Replacing the current token for a user
(env) shea@Sheas-MacBook-Pro open-personen % python src/manage.py generate_token user2
Replace existing token for user2? [yes/no] yes
API token: 2f5f22beaf743940e649a176cf56e199d91c4960

# Not creating new token but returning the token already created
(env) shea@Sheas-MacBook-Pro open-personen % python src/manage.py generate_token user2
Replace existing token for user2? [yes/no] no
API token: 2f5f22beaf743940e649a176cf56e199d91c4960

# Not asking for input and just recreating the token
(env) shea@Sheas-MacBook-Pro open-personen % python src/manage.py generate_token user2 --no-input
API token: fe8a3c35c535236d59e74e03456095965b874f15
(env) shea@Sheas-MacBook-Pro open-personen % python src/manage.py generate_token user2 --noinput 
API token: 31198cf3b9c89777dff2e656ccb6d13b40a30ca7
(env) shea@Sheas-MacBook-Pro open-personen %
```

2020-11-13 11:47 UTC, stevenbal approved these changes

2020-11-13 11:47 UTC, stevenbal commented on src/openpersonen/token/management/commands/generate_token.py
> +            dest="interactive",
Does `action="store_false"` negate the input to this command? If so, :+1:

2020-11-13 12:23 UTC, joeribekker requested changes
Please change documentation where it still says "Generated" instead of "API token" as output.

2020-11-13 12:55 UTC, shea-maykinmedia commented
@joeribekker Which documentation?

2020-11-13 13:03 UTC, shea-maykinmedia commented on src/openpersonen/token/management/commands/generate_token.py
> +            dest="interactive",
Basically yes.  `--noinput` is optional so if the user adds `--noinput` than this value is `True` and if it's not give it's `False`.

Eg.
```
(env) shea@Sheas-MacBook-Pro open-personen % python src/manage.py generate_token test1 
Interactive: True
API token: b04f40b6d4ea6a24d1cb51b64b224efe26f6f006
(env) shea@Sheas-MacBook-Pro open-personen % python src/manage.py generate_token test1 --noinput
Interactive: False
API token: 4e6db2e9646c9e7d8452f9771b1510ef0764afe8
(env) shea@Sheas-MacBook-Pro open-personen % 
```

2020-11-16 09:17 UTC, joeribekker commented
@shea-maykinmedia https://open-personen.readthedocs.io/en/latest/installation/authorizations.html#installation-authorizations

2020-11-16 15:19 UTC, shea-maykinmedia commented
@joeribekker Documentation has been updated :)

2020-11-16 15:34 UTC, joeribekker approved these changes

2020-11-16 15:34 UTC, merged