[WIP] Implement conversion service
maykinmedia/open-personen pull request #162
Opened 2020-11-18 09:32 UTC by shea-maykinmedia

Fixes #150

2020-11-19 13:40 UTC, joeribekker requested changes
This conversion cannot be part of the same API spec as the BRP API and i miss documentation on this feature :)

2020-11-20 13:58 UTC, shea-maykinmedia commented
Convert endpoints have been moved out of the BRP endpoints and documentation can be found here https://github.com/maykinmedia/open-personen/blob/feature/converter-endpoints/docs/convert/index.rst.

2020-12-21 09:14 UTC, joeribekker approved these changes

2020-12-21 09:54 UTC, merged

2020-12-21 09:58 UTC, joeribekker commented on docs/convert/index.rst
> +Convert Service
Conversion service

2020-12-21 09:58 UTC, joeribekker commented on docs/convert/index.rst
> +The conversion service allows converting Open Personen API requests to StUF-BG requests and
"converting Open Personen API requests" -> "converting BRP API requests"

2020-12-21 09:58 UTC, joeribekker commented on docs/convert/index.rst
> +StUF-BG responses to Open Personen API responses.  The conversion service does not make any
"to Open Personen API responses" -> "to BRP API responses"