Implement country code
maykinmedia/open-personen pull request #173
Opened 2020-12-03 15:00 UTC by shea-maykinmedia

Fixes #166 

Also adds a management command to create Country Code instances through a management command.

2020-12-03 15:17 UTC, shea-maykinmedia commented on src/openpersonen/features/country_code/models.py
> +class CountryCode(CodeAndOmschrijving):
The reason for putting all the code in the `CodeAndOmschrijving` model is that the next two stories are different models with a code and omschrijving properties so I think it makes sense to just do this now.

2020-12-07 10:29 UTC, stevenbal requested changes

2020-12-07 10:29 UTC, stevenbal commented on src/openpersonen/features/country_code_and_omschrijving/management/commands/import_country_codes_and_omschrijving.py
> +            return exit(1)
This could probably be combined by raising a `CommandError` (https://docs.djangoproject.com/en/3.1/howto/custom-management-commands/#django.core.management.CommandError)

```suggestion
            raise CommandError("Please specify a url or file, not both")
```

2020-12-07 10:29 UTC, stevenbal commented on src/openpersonen/features/country_code_and_omschrijving/management/commands/import_country_codes_and_omschrijving.py
> +        self.stdout.write(f"Done! {num_rows} imported!")
I think it's better to use `bulk_create` here (https://docs.djangoproject.com/en/3.1/ref/models/querysets/#bulk-create)

```suggestion
        countries = [CountryCodeAndOmschrijving(code=row[0], omschrijving=row[1]) for row in rows]
        CountryCodeAndOmschrijving.objects.bulk_create(countries)
        
        self.stdout.write(f"Done! {len(countries)} imported!")
```

2020-12-07 10:29 UTC, stevenbal commented on src/openpersonen/contrib/stufbg/converters/ingeschreven_persoon.py
> +                    instance_xml_dict.get(f"{prefix}:inp.geboorteLand", "string")
Not very important, but since `0` is used as the default everywhere else, I'd expect that here too
```suggestion
                    instance_xml_dict.get(f"{prefix}:inp.geboorteLand", "0")
```

2020-12-07 10:35 UTC, stevenbal commented on src/openpersonen/api/tests/test_data/ingeschreven_persoon.py
> +                "land": {"code": "6030", "omschrijving": "Nederland"},
Shouldn't this be an integer?
```suggestion
                "land": {"code": 6030, "omschrijving": "Nederland"},
```

2020-12-07 13:05 UTC, shea-maykinmedia commented on src/openpersonen/api/tests/test_data/ingeschreven_persoon.py
> +                "land": {"code": "6030", "omschrijving": "Nederland"},
According to VNG the code should be returned as a string.  

A bit odd but they do give 
```
"land": {
   "code": "6030",
   "omschrijving": "Nederland"
}
```
as an example.

2020-12-07 13:14 UTC, stevenbal approved these changes

2020-12-07 14:46 UTC, merged