Handle no certificate
maykinmedia/open-personen pull request #185
Opened 2021-04-14 09:06 UTC by shea-maykinmedia

Implement first point of https://github.com/maykinmedia/open-personen/issues/184

Since the certificate is not required when using the Stuf-BG client we need to handle the case it's not set.

2021-04-14 09:12 UTC, shea-maykinmedia commented
CI seems to be failing because the test file we used for the quickstart test now has a different name.  Verifying the fix locally.

2021-04-14 09:48 UTC, shea-maykinmedia commented
I can't think of a good way to test this with a unit test but I have tested with Postman by setting up the client to make calls to http://fieldlab.westeurope.cloudapp.azure.com:8081/brp/ with and without a certificate.

2021-04-21 08:34 UTC, joeribekker requested changes
> I can't think of a good way to test this with a unit test but I have tested with Postman by setting up the client to make calls to http://fieldlab.westeurope.cloudapp.azure.com:8081/brp/ with and without a certificate.

Seems not that hard to me? If you think about what you want to test here, it's just that you can make requests with and without a client certificate without an exception being raised.

```python
from django.test.testcases import LiveServerTestCase
import requests
import os

class TestThis(LiveServerTestCase):
    def test_with_cert(self):
        ssl_crt = os.path.join(os.path.dirname(__file__), "mocks.crt")
        ssl_key = os.path.join(os.path.dirname(__file__), "mocks.key")
        response = requests.post(self.live_server_url, data={"foo": "bar"}, cert=(ssl_crt, ssl_key))
        self.assertEqual(response.status_code, 403)

    def test_without_cert(self):
        ssl_crt = None
        ssl_key = None
        response = requests.post(self.live_server_url, data={"foo": "bar"}, cert=(ssl_crt, ssl_key))
        self.assertEqual(response.status_code, 403)
```

You can see the mock certs I used here: https://github.com/open-zaak/open-zaak/pull/905/files#diff-e13250ae16c3b384d30701eb8e0b0d05f62364aaeb1cc9cfc6e2f1f90c54e8f1

2021-04-23 07:27 UTC, shea-maykinmedia commented
Okay,  I wasn't sure if we wanted tests like this since they're essentially testing the `requests` library rather than our own code but I suppose it's good to make sure we're using the 3rd party library correctly so I've added the unit tests.

2021-04-23 07:40 UTC, joeribekker commented
Well, no. The testcode i wrote above was just to demonstrate it can be tested. The test is just about handling none or actual certificates right? Before, the app crashed when no certs where added?

2021-04-23 07:43 UTC, joeribekker requested changes

2021-04-23 07:43 UTC, joeribekker commented on src/openpersonen/contrib/stufbg/tests/test_client.py
> +        self.assertEqual(response.status_code, 403)
This was just an example to show it can be tested with dummy and no certificates, no need to test the requests library (i just added requests to show it works but you should use the usual route like `client.get_,,,,`

2021-04-23 11:36 UTC, shea-maykinmedia commented
Ya, the app did crash previously when no certificates were added.  I think adding the test `test_making_request_without_certificates` validates that a request will be made without crashing when no certificate is added so I'll remove the other tests I added since they shouldn't be needed.

2021-04-23 14:04 UTC, joeribekker approved these changes

2021-04-23 14:31 UTC, merged