[WIP] Implement filters
maykinmedia/open-personen pull request #53
Opened 2020-08-28 09:03 UTC by shea-maykinmedia

Implement the filtering described in https://github.com/maykinmedia/open-personen/issues/32

2020-08-28 10:24 UTC, shea-maykinmedia commented on src/openpersonen/api/data_classes/ingeschreven_personen.py
> +        return [cls(**instance_dict)]
This relates to https://github.com/maykinmedia/open-personen/issues/54 .  

Since we only have one example of a Stuf-BG request which is getting a single person with a BSN I'm not sure what to expect to get from the client if multiple people are returned or none are returned in the XML.  

In those cases we'll want to return a list of instances (or an empty list) so I'm artificially returning a list of instances here so that when we know what the Stuf-BG client will return only this function should need to change.

2020-08-28 10:28 UTC, shea-maykinmedia commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +        filters_values_dict.pop('naam__geslachtsnaam', 0)
I'm not sure how I feel about changing the dict here and in the other functions.

I don't think having side effects in functions is good programming practice however we do want this to be done so if it wasn't done here we'd need to check the result of this function in `get_filters_with_values` and then call another function to do this work which would add a lot of lines of code. 

If you have any other suggestions I'm happy to hear them. :)

2020-08-28 10:30 UTC, shea-maykinmedia commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +        # When retrieving a collection of people, at least one of the six following combinations must be included
This checks the rules defined here. https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/specificatie/openapi.yaml#/ingeschrevenpersonen/ingeschrevenNatuurlijkPersonen

I think we'll eventually want this same documentation in our own swagger/redoc but I'm not sure if more code comments should be added here to be clear to the next developer to look at this.  Thoughts?

2020-08-28 13:36 UTC, stevenbal requested changes

2020-08-28 13:36 UTC, stevenbal commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +        # When retrieving a collection of people, at least one of the six following combinations must be included
I agree that this should also be included in our own OAS, but that can come later I think. For now, I think adding a comment with the link you sent might be good, such that there is at least a reference to the validation (without having a huge comment explaining it)

2020-08-28 13:36 UTC, stevenbal commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +        filters_values_dict.pop('naam__geslachtsnaam', 0)
I'm not sure why it is needed to modify `filters_values_dict`? Couldn't you do something like this to check whether at least one of the conditions is met?

```python
def check_conditions(filters_values_dict):
    if 'geboorte__datum' in filters_values_dict and 'naam__geslachtsnaam' in filters_values_dict:
        return True
    if <second condition>:
        return True
    etc.
```
Also nitpicking, but I would probably use `key in dict` as opposed to `dict.get(key)` here, since the value is not actually being used

2020-08-28 13:36 UTC, stevenbal commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +            raise ValueError('Incorrect combination of filters')
In relation to my other comment, I think this could be changed to:

```python
if not check_conditions(filters_with_values):
    raise ValueError
```

Usually, we would use a `ValidationError` for this instead of `ValueError`, but that's not a major issue I think

2020-08-28 13:36 UTC, stevenbal commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +        instances = IngeschrevenPersoon.list(filters)
Not sure how important, but right now I don't think there is a check for invalid query parameters (as in, filters not defined in the filter class). You might be able to use this mixin from vng-api-common for this: https://github.com/VNG-Realisatie/vng-api-common/blob/master/vng_api_common/viewsets.py#L26

2020-08-28 13:46 UTC, shea-maykinmedia commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +        filters_values_dict.pop('naam__geslachtsnaam', 0)
`I'm not sure why it is needed to modify filters_values_dict?`. 

Can you double check this 
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/specificatie/openapi.yaml#/ingeschrevenpersonen/ingeschrevenNatuurlijkPersonen 
since I'm not certain that Google translated it properly.  My understanding is that if one part of the combination is missing then we should remove the other parts of the combination.  

Eg. For the first combination (geboorte__datum and naam__geslachtsnaam) if geboorte_datum is given but naam_geslachtnaam is not then we do not want to filter on geboorte_datum.  

This could be wrong though and if it is then `filters_values_dict` would not need to be modified and I can change this.

I will change the code to use `key in dict` though. :)

2020-08-28 13:50 UTC, shea-maykinmedia commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +            raise ValueError('Incorrect combination of filters')
Ya, I wasn't sure which error would be better to use. :p I will use change this to `ValidationError` for consistency with our other projects.

2020-08-28 13:56 UTC, shea-maykinmedia commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +        instances = IngeschrevenPersoon.list(filters)
Ya, since these filters are used like this https://github.com/maykinmedia/open-personen/blob/implement-filters/src/openpersonen/api/request_templates/RequestIngeschrevenPersoon.xml#L46-L107 if the user passes invalid query parameters they'll just get ignored. 

I'm not sure if this is okay behaviour or not.

2020-08-28 13:56 UTC, stevenbal commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +        filters_values_dict.pop('naam__geslachtsnaam', 0)
Ah of course, I forgot it was in Dutch :p. It says that "At least one of the six conditions must be met" and that "these six combinations may be combined with any other query parameters, but within every combination, the mentioned fields are required" (so within those six mention, this second comment is a bit redundant I think).

For some of the conditions you might have to use `.get`, I kind of glanced over the extra conditions for some parameters (like `naam__geslachtsnaam`, where the value should be at least 2 characters long or a wildcard)

2020-08-28 13:58 UTC, stevenbal commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +        instances = IngeschrevenPersoon.list(filters)
Ah I see, then I don't think it is necessary to add right now. I not sure how strict the API needs to be with regards to invalid/unknown query parameters? @joeribekker

2020-08-31 08:16 UTC, shea-maykinmedia commented on src/openpersonen/api/views/ingeschreven_persoon.py
> +        instances = IngeschrevenPersoon.list(filters)
Since we have this ticket here https://github.com/maykinmedia/open-personen/issues/43 I think these concerns are covered by this ticket so I'm going to mark this as resolved since it'll be covered later. :)

2020-08-31 09:08 UTC, shea-maykinmedia commented
@stevenbal I spoke with @joeribekker and he said that with the filters exactly combination of filters should be present, otherwise a bad request should be returned.

I've updated the code to handle this so I think this should be good to merge.  Can you take another look when you have time.

2020-08-31 10:57 UTC, stevenbal approved these changes

2020-08-31 11:36 UTC, merged