[WIP] Add travis schema check
maykinmedia/open-personen pull request #96
Opened 2020-09-24 14:50 UTC by shea-maykinmedia

Solution for https://github.com/maykinmedia/open-personen/issues/38

2020-09-30 08:07 UTC, joeribekker requested changes
Small change requests.

Be carefull not to include too much in one PR. Deletion of default files should have been in a different PR, but ok for now.

2020-09-30 08:07 UTC, joeribekker commented on src/openpersonen/urls.py
> -    path("", TemplateView.as_view(template_name="master.html")),
I think we should still have a master template/homepage but I'll make a ticket for it.

2020-09-30 08:07 UTC, joeribekker commented on src/resources.md
> +# Resources
This file can be deleted. Can also add it to .gitignore to prevent future inclusion.

It's not accurate and it's not relevant for this project.

2020-09-30 08:07 UTC, joeribekker commented on src/swagger2.0.json
> +{
This file can also be deleted. Can also add it to .gitignore to prevent future inclusion.

It's not relevant for this project.

2020-10-01 07:46 UTC, shea-maykinmedia commented on src/openpersonen/urls.py
> -    path("", TemplateView.as_view(template_name="master.html")),
👍

2020-10-01 10:32 UTC, joeribekker approved these changes

2020-10-01 10:32 UTC, merged